#Configurations for snort 2.9.0.4

engines:
 - engine: snort-2.9.0.4-etpro-base
   type: snort
   version: 2.9.0.4
   syntax_version: 2.9.0
   summary: "snort 2.9.0.4 base config with etpro rules"
   path: "/opt/snort2904/bin/snort"
   logdir: "/opt/snort2904/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2904/etc/snort2904.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2904/etc/etpro/snort2904-etpro-base.conf"

 - engine: snort-2.9.0.4-etpro-all
   type: snort
   version: 2.9.0.4
   syntax_version: 2.9.0
   summary: "snort 2.9.0.4 all config with etpro rules"
   path: "/opt/snort2904/bin/snort"
   logdir: "/opt/snort2904/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2904/etc/snort2904.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2904/etc/etpro/snort2904-etpro-all.conf"

 - engine: snort-2.9.0.4-etopen-base
   type: snort
   version: 2.9.0.4
   syntax_version: 2.9.0
   summary: "snort 2.9.0.4 base config with etopen rules"
   path: "/opt/snort2904/bin/snort"
   logdir: "/opt/snort2904/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2904/etc/snort2904.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2904/etc/etopen/snort2904-etopen-base.conf"

 - engine: snort-2.9.0.4-etopen-all
   type: snort
   version: 2.9.0.4
   syntax_version: 2.9.0
   summary: "snort 2.9.0.4 all config with etopen rules"
   path: "/opt/snort2904/bin/snort"
   logdir: "/opt/snort2904/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2904/etc/snort2904.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2904/etc/etopen/snort2904-etopen-all.conf"

