# Configurations avilable for snort 2.4.5

engines:
# With open rules
  - engine: snort245open
    type: snort
    version: 2.4.5
    syntax_version: 2.4.5
    summary: "snort 2.4.5 with config of ET open rules"
    path: "/opt/snort245/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort245/etc/snort-et-open.conf"
    configtpl: "/opt/snort245/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.4.0/open/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

# With Pro rules
  - engine: snort245pro
    type: snort
    version: 2.4.5
    syntax_version: 2.4.5
    summary: "snort 2.4.5 with config of ET pro rules"
    path: "/opt/snort245/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort245/etc/snort-et-pro.conf"
    configtpl: "/opt/snort245/etc/snort.conf.tpl"
    customrules: "/opt/ruledump/snort-2.4.0/etpro/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

