#Configurations for snort 2.9.3

engines:
 - engine: snort-2.9.3-etpro-base
   type: snort
   version: 2.9.3
   syntax_version: 2.9.0
   summary: "snort 2.9.3 base config with etpro rules"
   path: "/opt/snort293/bin/snort"
   logdir: "/opt/snort293/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort293/etc/snort293.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort293/etc/etpro/snort293-etpro-base.conf"

 - engine: snort-2.9.3-etpro-all
   type: snort
   version: 2.9.3
   syntax_version: 2.9.0
   summary: "snort 2.9.3 all config with etpro rules"
   path: "/opt/snort293/bin/snort"
   logdir: "/opt/snort293/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort293/etc/snort293.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort293/etc/etpro/snort293-etpro-all.conf"

 - engine: snort-2.9.3-etopen-base
   type: snort
   version: 2.9.3
   syntax_version: 2.9.0
   summary: "snort 2.9.3 base config with etopen rules"
   path: "/opt/snort293/bin/snort"
   logdir: "/opt/snort293/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort293/etc/snort293.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort293/etc/etopen/snort293-etopen-base.conf"

 - engine: snort-2.9.3-etopen-all
   type: snort
   version: 2.9.3
   syntax_version: 2.9.0
   summary: "snort 2.9.3 all config with etopen rules"
   path: "/opt/snort293/bin/snort"
   logdir: "/opt/snort293/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort293/etc/snort293.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort293/etc/etopen/snort293-etopen-all.conf"

 - engine: snort-2.9.3-test-test
   type: snort
   version: 2.9.3
   syntax_version: 2.9.0
   summary: "snort 2.9.3 test config with test rules"
   path: "/opt/snort293/bin/snort"
   logdir: "/opt/snort293/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort293/etc/snort293.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort293/etc/test/snort293-test-test.conf"

