#Configurations for snort 2.9.2.2

engines:
 - engine: snort-2.9.2.2-etpro-base
   type: snort
   version: 2.9.2.2
   syntax_version: 2.9.0
   summary: "snort 2.9.2.2 base config with etpro rules"
   path: "/opt/snort2922/bin/snort"
   logdir: "/opt/snort2922/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2922/etc/snort2922.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2922/etc/etpro/snort2922-etpro-base.conf"

 - engine: snort-2.9.2.2-etpro-all
   type: snort
   version: 2.9.2.2
   syntax_version: 2.9.0
   summary: "snort 2.9.2.2 all config with etpro rules"
   path: "/opt/snort2922/bin/snort"
   logdir: "/opt/snort2922/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2922/etc/snort2922.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2922/etc/etpro/snort2922-etpro-all.conf"

 - engine: snort-2.9.2.2-etopen-base
   type: snort
   version: 2.9.2.2
   syntax_version: 2.9.0
   summary: "snort 2.9.2.2 base config with etopen rules"
   path: "/opt/snort2922/bin/snort"
   logdir: "/opt/snort2922/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2922/etc/snort2922.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2922/etc/etopen/snort2922-etopen-base.conf"

 - engine: snort-2.9.2.2-etopen-all
   type: snort
   version: 2.9.2.2
   syntax_version: 2.9.0
   summary: "snort 2.9.2.2 all config with etopen rules"
   path: "/opt/snort2922/bin/snort"
   logdir: "/opt/snort2922/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2922/etc/snort2922.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2922/etc/etopen/snort2922-etopen-all.conf"

