#Configurations for snort 2.8.4.1

engines:
 - engine: snort-2.8.4.1-etpro-base
   type: snort
   version: 2.8.4.1
   syntax_version: 2.8.4
   summary: "snort 2.8.4.1 base config with etpro rules"
   path: "/opt/snort2841/bin/snort"
   logdir: "/opt/snort2841/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2841/etc/snort2841.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2841/etc/etpro/snort2841-etpro-base.conf"

 - engine: snort-2.8.4.1-etpro-all
   type: snort
   version: 2.8.4.1
   syntax_version: 2.8.4
   summary: "snort 2.8.4.1 all config with etpro rules"
   path: "/opt/snort2841/bin/snort"
   logdir: "/opt/snort2841/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2841/etc/snort2841.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2841/etc/etpro/snort2841-etpro-all.conf"

 - engine: snort-2.8.4.1-etopen-base
   type: snort
   version: 2.8.4.1
   syntax_version: 2.8.4
   summary: "snort 2.8.4.1 base config with etopen rules"
   path: "/opt/snort2841/bin/snort"
   logdir: "/opt/snort2841/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2841/etc/snort2841.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2841/etc/etopen/snort2841-etopen-base.conf"

 - engine: snort-2.8.4.1-etopen-all
   type: snort
   version: 2.8.4.1
   syntax_version: 2.8.4
   summary: "snort 2.8.4.1 all config with etopen rules"
   path: "/opt/snort2841/bin/snort"
   logdir: "/opt/snort2841/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2841/etc/snort2841.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2841/etc/etopen/snort2841-etopen-all.conf"

