#Configurations for snort 2.9.2.3

engines:
 - engine: snort-2.9.2.3-etpro-base
   type: snort
   version: 2.9.2.3
   syntax_version: 2.9.0
   summary: "snort 2.9.2.3 base config with etpro rules"
   path: "/opt/snort2923/bin/snort"
   logdir: "/opt/snort2923/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2923/etc/snort2923.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2923/etc/etpro/snort2923-etpro-base.conf"

 - engine: snort-2.9.2.3-etpro-all
   type: snort
   version: 2.9.2.3
   syntax_version: 2.9.0
   summary: "snort 2.9.2.3 all config with etpro rules"
   path: "/opt/snort2923/bin/snort"
   logdir: "/opt/snort2923/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2923/etc/snort2923.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2923/etc/etpro/snort2923-etpro-all.conf"

 - engine: snort-2.9.2.3-etopen-base
   type: snort
   version: 2.9.2.3
   syntax_version: 2.9.0
   summary: "snort 2.9.2.3 base config with etopen rules"
   path: "/opt/snort2923/bin/snort"
   logdir: "/opt/snort2923/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2923/etc/snort2923.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2923/etc/etopen/snort2923-etopen-base.conf"

 - engine: snort-2.9.2.3-etopen-all
   type: snort
   version: 2.9.2.3
   syntax_version: 2.9.0
   summary: "snort 2.9.2.3 all config with etopen rules"
   path: "/opt/snort2923/bin/snort"
   logdir: "/opt/snort2923/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2923/etc/snort2923.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2923/etc/etopen/snort2923-etopen-all.conf"

