# Configurations avilable for snort 2.8.6.1

engines:
# With open rules
  - engine: snort2861open
    type: snort
    version: 2.8.6.1
    syntax_version: 2.8.6
    summary: "snort 2.8.6.1 with config of ET open rules"
    path: "/opt/snort2861/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2861/etc/snort-et-open.conf"
    configtpl: "/opt/snort2861/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.6/open/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

# With Pro rules
  - engine: snort2861pro
    type: snort
    version: 2.8.6.1
    syntax_version: 2.8.6
    summary: "snort 2.8.6.1 with config of ET pro rules"
    path: "/opt/snort2861/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2861/etc/snort-et-pro.conf"
    configtpl: "/opt/snort2861/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.6/etpro/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

# Open rules with fast_pattern_debug
  - engine: snort2861openfpdebug
    type: snort
    version: 2.8.6.1
    syntax_version: 2.8.6
    summary: "snort 2.8.6.1 with config of ET open rules and fast_pattern debug"
    path: "/opt/snort2861/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2861/etc/snort-et-open-fp-debug.conf"
    configtpl: "/opt/snort2861/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.6/open/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

# Pro rules with fast_pattern_debug
  - engine: snort2861profpdebug
    type: snort
    version: 2.8.6.1
    syntax_version: 2.8.6
    summary: "snort 2.8.6.1 with config of ET pro rules and fast_pattern debug"
    path: "/opt/snort2861/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2861/etc/snort-et-pro-fp-debug.conf"
    configtpl: "/opt/snort2861/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.6/etpro/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes
