#Configurations for snort 2.9.0.5

engines:
 - engine: snort-2.9.0.5-etpro-base
   type: snort
   version: 2.9.0.5
   syntax_version: 2.9.0
   summary: "snort 2.9.0.5 base config with etpro rules"
   path: "/opt/snort2905/bin/snort"
   logdir: "/opt/snort2905/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2905/etc/snort2905.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2905/etc/etpro/snort2905-etpro-base.conf"

 - engine: snort-2.9.0.5-etpro-all
   type: snort
   version: 2.9.0.5
   syntax_version: 2.9.0
   summary: "snort 2.9.0.5 all config with etpro rules"
   path: "/opt/snort2905/bin/snort"
   logdir: "/opt/snort2905/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2905/etc/snort2905.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2905/etc/etpro/snort2905-etpro-all.conf"

 - engine: snort-2.9.0.5-etopen-base
   type: snort
   version: 2.9.0.5
   syntax_version: 2.9.0
   summary: "snort 2.9.0.5 base config with etopen rules"
   path: "/opt/snort2905/bin/snort"
   logdir: "/opt/snort2905/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2905/etc/snort2905.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2905/etc/etopen/snort2905-etopen-base.conf"

 - engine: snort-2.9.0.5-etopen-all
   type: snort
   version: 2.9.0.5
   syntax_version: 2.9.0
   summary: "snort 2.9.0.5 all config with etopen rules"
   path: "/opt/snort2905/bin/snort"
   logdir: "/opt/snort2905/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2905/etc/snort2905.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2905/etc/etopen/snort2905-etopen-all.conf"

 - engine: snort-2.9.0.5-test-test
   type: snort
   version: 2.9.0.5
   syntax_version: 2.9.0
   summary: "snort 2.9.0.5 test config with test rules"
   path: "/opt/snort2905/bin/snort"
   logdir: "/opt/snort2905/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort2905/etc/snort2905.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort2905/etc/test/snort2905-test-test.conf"

