#Configurations for snort 2.9.4

engines:
 - engine: snort-2.9.4-etpro-base
   type: snort
   version: 2.9.4
   syntax_version: 2.9.0
   summary: "snort 2.9.4 base config with etpro rules"
   path: "/opt/snort294/bin/snort"
   logdir: "/opt/snort294/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort294/etc/snort294.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort294/etc/etpro/snort294-etpro-base.conf"

 - engine: snort-2.9.4-etpro-all
   type: snort
   version: 2.9.4
   syntax_version: 2.9.0
   summary: "snort 2.9.4 all config with etpro rules"
   path: "/opt/snort294/bin/snort"
   logdir: "/opt/snort294/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort294/etc/snort294.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort294/etc/etpro/snort294-etpro-all.conf"

 - engine: snort-2.9.4-etopen-base
   type: snort
   version: 2.9.4
   syntax_version: 2.9.0
   summary: "snort 2.9.4 base config with etopen rules"
   path: "/opt/snort294/bin/snort"
   logdir: "/opt/snort294/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort294/etc/snort294.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort294/etc/etopen/snort294-etopen-base.conf"

 - engine: snort-2.9.4-etopen-all
   type: snort
   version: 2.9.4
   syntax_version: 2.9.0
   summary: "snort 2.9.4 all config with etopen rules"
   path: "/opt/snort294/bin/snort"
   logdir: "/opt/snort294/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort294/etc/snort294.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort294/etc/etopen/snort294-etopen-all.conf"

 - engine: snort-2.9.4-test-test
   type: snort
   version: 2.9.4
   syntax_version: 2.9.0
   summary: "snort 2.9.4 test config with test rules"
   path: "/opt/snort294/bin/snort"
   logdir: "/opt/snort294/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/snort294/etc/snort294.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/snort294/etc/test/snort294-test-test.conf"

