# Configurations avilable for snort 2.8.4.1

engines:
# With open rules
  - engine: snort2841open
    type: snort
    version: 2.8.4.1
    syntax_version: 2.8.4
    summary: "snort 2.8.4.1 with config of ET open rules"
    path: "/opt/snort2841/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2841/etc/snort-et-open.conf"
    # For specifying custom rules, we use the following template
    configtpl: "/opt/snort2841/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.4/open/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes

# With Pro rules
  - engine: snort2841pro
    type: snort
    version: 2.8.4.1
    syntax_version: 2.8.4
    summary: "snort 2.8.4.1 with config of ET pro rules"
    path: "/opt/snort2841/bin/snort"
    logdir: "./logs/"
    config: "/opt/snort2841/etc/snort-et-pro.conf"
    configtpl: "/opt/snort2841/etc/snort.conf.tpl"
    customrules: "/opt/customrules/snort-2.8.4/etpro/all.rules"
    fastlog: "alert"
    perflog: "perf.txt"
    enable: yes
