# Configurations avilable for suricata 1.2.1

engines:
# With Base Open rules
  - engine: suricata-1.2.1-open-base
    type: suricata 
    version: 1.2.1
    syntax_version: 2.9.0
    summary: "suricata 1.2.1 base config with ET open rules"
    path: "/opt/suricata121/bin/suricata"
    logdir: "/opt/suricata121/var/log/"
    config: "/opt/suricata121/etc/etopen/suricata-121-et-open.yaml"
    # For specifying custom rules, we use the following template
    configtpl: "/opt/suricata121/etc/suricata.conf.tpl"
    customrules: "/opt/ruledump/suricata-1.2.1/etopen/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enable: yes

# With All Open rules
  - engine: suricata-1.2.1-open-all
    type: suricata
    version: 1.2.1
    syntax_version: 2.9.0
    summary: "suricata 1.2.1 base config with All ET open rules"
    path: "/opt/suricata121/bin/suricata"
    logdir: "/opt/suricata121/var/log/"
    config: "/opt/suricata121/etc/etopen/suricata-121-et-open-all.yaml"
    # For specifying custom rules, we use the following template
    configtpl: "/opt/suricata121/etc/suricata.conf.tpl"
    customrules: "/opt/ruledump/suricata-1.2.1/etopen/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enable: yes

# With Pro rules
  - engine: suricata121pro
    type: suricata
    version: 1.2.1
    syntax_version: 2.9.0
    summary: "suricata 1.2.1 with config of ET pro rules"
    path: "/opt/suricata121/bin/suricata"
    logdir: "./logs/"
    config: "/opt/suricata121/etc/suricata-et-pro.yaml"
    configtpl: "/opt/suricata121/etc/suricata.conf.tpl"
    customrules: "/opt/customrules/suricata-1.2.1/etpro/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enable: yes
