#Configurations for suricata 1.4.1JIT

engines:
 - engine: suricata-1.4.1JIT-etpro-base
   type: suricata
   version: 1.4.1JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4.1JIT base config with etpro rules"
   path: "/opt/suricata141JIT/bin/suricata"
   logdir: "/opt/suricata141JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141JIT/etc/suricata141JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141JIT/etc/etpro/suricata141JIT-etpro-base.yaml"

 - engine: suricata-1.4.1JIT-etpro-all
   type: suricata
   version: 1.4.1JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4.1JIT all config with etpro rules"
   path: "/opt/suricata141JIT/bin/suricata"
   logdir: "/opt/suricata141JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141JIT/etc/suricata141JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141JIT/etc/etpro/suricata141JIT-etpro-all.yaml"

 - engine: suricata-1.4.1JIT-etopen-base
   type: suricata
   version: 1.4.1JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4.1JIT base config with etopen rules"
   path: "/opt/suricata141JIT/bin/suricata"
   logdir: "/opt/suricata141JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141JIT/etc/suricata141JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141JIT/etc/etopen/suricata141JIT-etopen-base.yaml"

 - engine: suricata-1.4.1JIT-etopen-all
   type: suricata
   version: 1.4.1JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4.1JIT all config with etopen rules"
   path: "/opt/suricata141JIT/bin/suricata"
   logdir: "/opt/suricata141JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141JIT/etc/suricata141JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141JIT/etc/etopen/suricata141JIT-etopen-all.yaml"

 - engine: suricata-1.4.1JIT-test-test
   type: suricata
   version: 1.4.1JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4.1JIT test config with test rules"
   path: "/opt/suricata141JIT/bin/suricata"
   logdir: "/opt/suricata141JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141JIT/etc/suricata141JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141JIT/etc/test/suricata141JIT-test-test.yaml"

