# Suricata dev Configs available
engines:

  - engine: suricatadevopen
    type: suricata
    version: dev 
    syntax_version: 2.9.0
    summary: "suricata dev with config using ET open rules"
    path: "/opt/suricatadev/bin/suricata"
    logdir: "./logs/"
    config: "/opt/suricatadev/etc/suricata-et-open.yaml"
    configtpl: "/opt/suricatadev/etc/suricata.yaml.tpl"
    customrules: "/opt/customrules/suricata/open/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enabled: yes

  - engine: suricatadevpro
    type: suricata
    version: dev
    syntax_version: 2.9.0
    summary: "suricata dev with config using ET pro rules"
    path: "/opt/suricatadev/bin/suricata"
    logdir: "./logs/"
    config: "/opt/suricatadev/etc/suricata-et-pro.yaml"
    configtpl: "/opt/suricatadev/etc/suricata.yaml.tpl"
    customrules: "/opt/customrules/suricata/etpro/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enabled: yes

