#Configurations for suricata 1.3

engines:
 - engine: suricata-1.3-etpro-base
   type: suricata
   version: 1.3
   syntax_version: 1.3
   summary: "suricata 1.3 base config with etpro rules"
   path: "/opt/suricata13/bin/suricata"
   logdir: "/opt/suricata13/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13/etc/suricata13.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13/etc/etpro/suricata13-etpro-base.yaml"

 - engine: suricata-1.3-etpro-all
   type: suricata
   version: 1.3
   syntax_version: 1.3
   summary: "suricata 1.3 all config with etpro rules"
   path: "/opt/suricata13/bin/suricata"
   logdir: "/opt/suricata13/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13/etc/suricata13.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13/etc/etpro/suricata13-etpro-all.yaml"

 - engine: suricata-1.3-etopen-base
   type: suricata
   version: 1.3
   syntax_version: 1.3
   summary: "suricata 1.3 base config with etopen rules"
   path: "/opt/suricata13/bin/suricata"
   logdir: "/opt/suricata13/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13/etc/suricata13.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13/etc/etopen/suricata13-etopen-base.yaml"

 - engine: suricata-1.3-etopen-all
   type: suricata
   version: 1.3
   syntax_version: 1.3
   summary: "suricata 1.3 all config with etopen rules"
   path: "/opt/suricata13/bin/suricata"
   logdir: "/opt/suricata13/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13/etc/suricata13.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13/etc/etopen/suricata13-etopen-all.yaml"

