#Configurations for suricata 1.3.5

engines:
 - engine: suricata-1.3.5-etpro-base
   type: suricata
   version: 1.3.5
   syntax_version: 1.3.3
   summary: "suricata 1.3.5 base config with etpro rules"
   path: "/opt/suricata135/bin/suricata"
   logdir: "/opt/suricata135/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135/etc/suricata135.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135/etc/etpro/suricata135-etpro-base.yaml"

 - engine: suricata-1.3.5-etpro-all
   type: suricata
   version: 1.3.5
   syntax_version: 1.3.3
   summary: "suricata 1.3.5 all config with etpro rules"
   path: "/opt/suricata135/bin/suricata"
   logdir: "/opt/suricata135/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135/etc/suricata135.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135/etc/etpro/suricata135-etpro-all.yaml"

 - engine: suricata-1.3.5-etopen-base
   type: suricata
   version: 1.3.5
   syntax_version: 1.3.3
   summary: "suricata 1.3.5 base config with etopen rules"
   path: "/opt/suricata135/bin/suricata"
   logdir: "/opt/suricata135/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135/etc/suricata135.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135/etc/etopen/suricata135-etopen-base.yaml"

 - engine: suricata-1.3.5-etopen-all
   type: suricata
   version: 1.3.5
   syntax_version: 1.3.3
   summary: "suricata 1.3.5 all config with etopen rules"
   path: "/opt/suricata135/bin/suricata"
   logdir: "/opt/suricata135/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135/etc/suricata135.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135/etc/etopen/suricata135-etopen-all.yaml"

 - engine: suricata-1.3.5-test-test
   type: suricata
   version: 1.3.5
   syntax_version: 1.3.3
   summary: "suricata 1.3.5 test config with test rules"
   path: "/opt/suricata135/bin/suricata"
   logdir: "/opt/suricata135/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135/etc/suricata135.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135/etc/test/suricata135-test-test.yaml"

