# Suricata 1.0.2 Configs available
engines:

  - engine: suricata102open
    type: suricata
    version: 1.0.2
    syntax_version: 2.8.6
    summary: "suricata 1.0.2 with config using ET open rules"
    path: "/opt/suricata102/bin/suricata"
    logdir: "./logs/"
    config: "/opt/suricata102/etc/suricata-et-open.yaml"
    configtpl: "/opt/suricata102/etc/suricata.yaml.tpl"
    customrules: "/opt/customrules/suricata/open/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enabled: yes

  - engine: suricata102pro
    type: suricata
    version: 1.0.2
    syntax_version: 2.8.6
    summary: "suricata 1.0.2 with config using ET pro rules"
    path: "/opt/suricata102/bin/suricata"
    logdir: "./logs/"
    config: "/opt/suricata102/etc/suricata-et-pro.yaml"
    configtpl: "/opt/suricata102/etc/suricata.yaml.tpl"
    customrules: "/opt/customrules/suricata/etpro/all.rules"
    fastlog: "fast.log"
    perflog: "perf.txt"
    enabled: yes

