#Configurations for suricata 1.3.6JIT

engines:
 - engine: suricata-1.3.6JIT-etpro-base
   type: suricata
   version: 1.3.6JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.6JIT base config with etpro rules"
   path: "/opt/suricata136JIT/bin/suricata"
   logdir: "/opt/suricata136JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata136JIT/etc/suricata136JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata136JIT/etc/etpro/suricata136JIT-etpro-base.yaml"

 - engine: suricata-1.3.6JIT-etpro-all
   type: suricata
   version: 1.3.6JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.6JIT all config with etpro rules"
   path: "/opt/suricata136JIT/bin/suricata"
   logdir: "/opt/suricata136JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata136JIT/etc/suricata136JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata136JIT/etc/etpro/suricata136JIT-etpro-all.yaml"

 - engine: suricata-1.3.6JIT-etopen-base
   type: suricata
   version: 1.3.6JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.6JIT base config with etopen rules"
   path: "/opt/suricata136JIT/bin/suricata"
   logdir: "/opt/suricata136JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata136JIT/etc/suricata136JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata136JIT/etc/etopen/suricata136JIT-etopen-base.yaml"

 - engine: suricata-1.3.6JIT-etopen-all
   type: suricata
   version: 1.3.6JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.6JIT all config with etopen rules"
   path: "/opt/suricata136JIT/bin/suricata"
   logdir: "/opt/suricata136JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata136JIT/etc/suricata136JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata136JIT/etc/etopen/suricata136JIT-etopen-all.yaml"

 - engine: suricata-1.3.6JIT-test-test
   type: suricata
   version: 1.3.6JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.6JIT test config with test rules"
   path: "/opt/suricata136JIT/bin/suricata"
   logdir: "/opt/suricata136JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata136JIT/etc/suricata136JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata136JIT/etc/test/suricata136JIT-test-test.yaml"

