#Configurations for suricata 1.3JIT

engines:
 - engine: suricata-1.3JIT-etpro-base
   type: suricata
   version: 1.3JIT
   syntax_version: 1.3
   summary: "suricata 1.3JIT base config with etpro rules"
   path: "/opt/suricata13JIT/bin/suricata"
   logdir: "/opt/suricata13JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13JIT/etc/suricata13JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13JIT/etc/etpro/suricata13JIT-etpro-base.yaml"

 - engine: suricata-1.3JIT-etpro-all
   type: suricata
   version: 1.3JIT
   syntax_version: 1.3
   summary: "suricata 1.3JIT all config with etpro rules"
   path: "/opt/suricata13JIT/bin/suricata"
   logdir: "/opt/suricata13JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13JIT/etc/suricata13JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13JIT/etc/etpro/suricata13JIT-etpro-all.yaml"

 - engine: suricata-1.3JIT-etopen-base
   type: suricata
   version: 1.3JIT
   syntax_version: 1.3
   summary: "suricata 1.3JIT base config with etopen rules"
   path: "/opt/suricata13JIT/bin/suricata"
   logdir: "/opt/suricata13JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13JIT/etc/suricata13JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13JIT/etc/etopen/suricata13JIT-etopen-base.yaml"

 - engine: suricata-1.3JIT-etopen-all
   type: suricata
   version: 1.3JIT
   syntax_version: 1.3
   summary: "suricata 1.3JIT all config with etopen rules"
   path: "/opt/suricata13JIT/bin/suricata"
   logdir: "/opt/suricata13JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13JIT/etc/suricata13JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13JIT/etc/etopen/suricata13JIT-etopen-all.yaml"

 - engine: suricata-1.3JIT-test-test
   type: suricata
   version: 1.3JIT
   syntax_version: 1.3
   summary: "suricata 1.3JIT test config with test rules"
   path: "/opt/suricata13JIT/bin/suricata"
   logdir: "/opt/suricata13JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata13JIT/etc/suricata13JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata13JIT/etc/test/suricata13JIT-test-test.yaml"

