#Configurations for suricata 1.2.1

engines:
 - engine: suricata-1.2.1-etpro-base
   type: suricata
   version: 1.2.1
   syntax_version: 1.2
   summary: "suricata 1.2.1 base config with etpro rules"
   path: "/opt/suricata121/bin/suricata"
   logdir: "/opt/suricata121/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata121/etc/suricata121.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata121/etc/etpro/suricata121-etpro-base.yaml"

 - engine: suricata-1.2.1-etpro-all
   type: suricata
   version: 1.2.1
   syntax_version: 1.2
   summary: "suricata 1.2.1 all config with etpro rules"
   path: "/opt/suricata121/bin/suricata"
   logdir: "/opt/suricata121/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata121/etc/suricata121.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata121/etc/etpro/suricata121-etpro-all.yaml"

 - engine: suricata-1.2.1-etopen-base
   type: suricata
   version: 1.2.1
   syntax_version: 1.2
   summary: "suricata 1.2.1 base config with etopen rules"
   path: "/opt/suricata121/bin/suricata"
   logdir: "/opt/suricata121/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata121/etc/suricata121.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata121/etc/etopen/suricata121-etopen-base.yaml"

 - engine: suricata-1.2.1-etopen-all
   type: suricata
   version: 1.2.1
   syntax_version: 1.2
   summary: "suricata 1.2.1 all config with etopen rules"
   path: "/opt/suricata121/bin/suricata"
   logdir: "/opt/suricata121/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata121/etc/suricata121.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata121/etc/etopen/suricata121-etopen-all.yaml"

