#Configurations for suricata 1.4

engines:
 - engine: suricata-1.4-etpro-base
   type: suricata
   version: 1.4
   syntax_version: 1.3.3
   summary: "suricata 1.4 base config with etpro rules"
   path: "/opt/suricata14/bin/suricata"
   logdir: "/opt/suricata14/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14/etc/suricata14.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14/etc/etpro/suricata14-etpro-base.yaml"

 - engine: suricata-1.4-etpro-all
   type: suricata
   version: 1.4
   syntax_version: 1.3.3
   summary: "suricata 1.4 all config with etpro rules"
   path: "/opt/suricata14/bin/suricata"
   logdir: "/opt/suricata14/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14/etc/suricata14.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14/etc/etpro/suricata14-etpro-all.yaml"

 - engine: suricata-1.4-etopen-base
   type: suricata
   version: 1.4
   syntax_version: 1.3.3
   summary: "suricata 1.4 base config with etopen rules"
   path: "/opt/suricata14/bin/suricata"
   logdir: "/opt/suricata14/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14/etc/suricata14.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14/etc/etopen/suricata14-etopen-base.yaml"

 - engine: suricata-1.4-etopen-all
   type: suricata
   version: 1.4
   syntax_version: 1.3.3
   summary: "suricata 1.4 all config with etopen rules"
   path: "/opt/suricata14/bin/suricata"
   logdir: "/opt/suricata14/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14/etc/suricata14.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14/etc/etopen/suricata14-etopen-all.yaml"

 - engine: suricata-1.4-test-test
   type: suricata
   version: 1.4
   syntax_version: 1.3.3
   summary: "suricata 1.4 test config with test rules"
   path: "/opt/suricata14/bin/suricata"
   logdir: "/opt/suricata14/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14/etc/suricata14.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14/etc/test/suricata14-test-test.yaml"

