#Configurations for suricata 1.4.1

engines:
 - engine: suricata-1.4.1-etpro-base
   type: suricata
   version: 1.4.1
   syntax_version: 1.3.3
   summary: "suricata 1.4.1 base config with etpro rules"
   path: "/opt/suricata141/bin/suricata"
   logdir: "/opt/suricata141/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141/etc/suricata141.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141/etc/etpro/suricata141-etpro-base.yaml"

 - engine: suricata-1.4.1-etpro-all
   type: suricata
   version: 1.4.1
   syntax_version: 1.3.3
   summary: "suricata 1.4.1 all config with etpro rules"
   path: "/opt/suricata141/bin/suricata"
   logdir: "/opt/suricata141/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141/etc/suricata141.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141/etc/etpro/suricata141-etpro-all.yaml"

 - engine: suricata-1.4.1-etopen-base
   type: suricata
   version: 1.4.1
   syntax_version: 1.3.3
   summary: "suricata 1.4.1 base config with etopen rules"
   path: "/opt/suricata141/bin/suricata"
   logdir: "/opt/suricata141/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141/etc/suricata141.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141/etc/etopen/suricata141-etopen-base.yaml"

 - engine: suricata-1.4.1-etopen-all
   type: suricata
   version: 1.4.1
   syntax_version: 1.3.3
   summary: "suricata 1.4.1 all config with etopen rules"
   path: "/opt/suricata141/bin/suricata"
   logdir: "/opt/suricata141/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141/etc/suricata141.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141/etc/etopen/suricata141-etopen-all.yaml"

 - engine: suricata-1.4.1-test-test
   type: suricata
   version: 1.4.1
   syntax_version: 1.3.3
   summary: "suricata 1.4.1 test config with test rules"
   path: "/opt/suricata141/bin/suricata"
   logdir: "/opt/suricata141/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata141/etc/suricata141.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata141/etc/test/suricata141-test-test.yaml"

