#Configurations for suricata 1.3.5JIT

engines:
 - engine: suricata-1.3.5JIT-etpro-base
   type: suricata
   version: 1.3.5JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.5JIT base config with etpro rules"
   path: "/opt/suricata135JIT/bin/suricata"
   logdir: "/opt/suricata135JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135JIT/etc/suricata135JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135JIT/etc/etpro/suricata135JIT-etpro-base.yaml"

 - engine: suricata-1.3.5JIT-etpro-all
   type: suricata
   version: 1.3.5JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.5JIT all config with etpro rules"
   path: "/opt/suricata135JIT/bin/suricata"
   logdir: "/opt/suricata135JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135JIT/etc/suricata135JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135JIT/etc/etpro/suricata135JIT-etpro-all.yaml"

 - engine: suricata-1.3.5JIT-etopen-base
   type: suricata
   version: 1.3.5JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.5JIT base config with etopen rules"
   path: "/opt/suricata135JIT/bin/suricata"
   logdir: "/opt/suricata135JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135JIT/etc/suricata135JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135JIT/etc/etopen/suricata135JIT-etopen-base.yaml"

 - engine: suricata-1.3.5JIT-etopen-all
   type: suricata
   version: 1.3.5JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.5JIT all config with etopen rules"
   path: "/opt/suricata135JIT/bin/suricata"
   logdir: "/opt/suricata135JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135JIT/etc/suricata135JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135JIT/etc/etopen/suricata135JIT-etopen-all.yaml"

 - engine: suricata-1.3.5JIT-test-test
   type: suricata
   version: 1.3.5JIT
   syntax_version: 1.3.3
   summary: "suricata 1.3.5JIT test config with test rules"
   path: "/opt/suricata135JIT/bin/suricata"
   logdir: "/opt/suricata135JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata135JIT/etc/suricata135JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata135JIT/etc/test/suricata135JIT-test-test.yaml"

