#Configurations for suricata 1.3.1JIT

engines:
 - engine: suricata-1.3.1JIT-etpro-base
   type: suricata
   version: 1.3.1JIT
   syntax_version: 1.3.1
   summary: "suricata 1.3.1JIT base config with etpro rules"
   path: "/opt/suricata131JIT/bin/suricata"
   logdir: "/opt/suricata131JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata131JIT/etc/suricata131JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata131JIT/etc/etpro/suricata131JIT-etpro-base.yaml"

 - engine: suricata-1.3.1JIT-etpro-all
   type: suricata
   version: 1.3.1JIT
   syntax_version: 1.3.1
   summary: "suricata 1.3.1JIT all config with etpro rules"
   path: "/opt/suricata131JIT/bin/suricata"
   logdir: "/opt/suricata131JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata131JIT/etc/suricata131JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata131JIT/etc/etpro/suricata131JIT-etpro-all.yaml"

 - engine: suricata-1.3.1JIT-etopen-base
   type: suricata
   version: 1.3.1JIT
   syntax_version: 1.3.1
   summary: "suricata 1.3.1JIT base config with etopen rules"
   path: "/opt/suricata131JIT/bin/suricata"
   logdir: "/opt/suricata131JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata131JIT/etc/suricata131JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata131JIT/etc/etopen/suricata131JIT-etopen-base.yaml"

 - engine: suricata-1.3.1JIT-etopen-all
   type: suricata
   version: 1.3.1JIT
   syntax_version: 1.3.1
   summary: "suricata 1.3.1JIT all config with etopen rules"
   path: "/opt/suricata131JIT/bin/suricata"
   logdir: "/opt/suricata131JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata131JIT/etc/suricata131JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata131JIT/etc/etopen/suricata131JIT-etopen-all.yaml"

 - engine: suricata-1.3.1JIT-test-test
   type: suricata
   version: 1.3.1JIT
   syntax_version: 1.3.1
   summary: "suricata 1.3.1JIT test config with test rules"
   path: "/opt/suricata131JIT/bin/suricata"
   logdir: "/opt/suricata131JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata131JIT/etc/suricata131JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata131JIT/etc/test/suricata131JIT-test-test.yaml"

