#Configurations for suricata 1.4JIT

engines:
 - engine: suricata-1.4JIT-etpro-base
   type: suricata
   version: 1.4JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4JIT base config with etpro rules"
   path: "/opt/suricata14JIT/bin/suricata"
   logdir: "/opt/suricata14JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14JIT/etc/suricata14JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14JIT/etc/etpro/suricata14JIT-etpro-base.yaml"

 - engine: suricata-1.4JIT-etpro-all
   type: suricata
   version: 1.4JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4JIT all config with etpro rules"
   path: "/opt/suricata14JIT/bin/suricata"
   logdir: "/opt/suricata14JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14JIT/etc/suricata14JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14JIT/etc/etpro/suricata14JIT-etpro-all.yaml"

 - engine: suricata-1.4JIT-etopen-base
   type: suricata
   version: 1.4JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4JIT base config with etopen rules"
   path: "/opt/suricata14JIT/bin/suricata"
   logdir: "/opt/suricata14JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14JIT/etc/suricata14JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14JIT/etc/etopen/suricata14JIT-etopen-base.yaml"

 - engine: suricata-1.4JIT-etopen-all
   type: suricata
   version: 1.4JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4JIT all config with etopen rules"
   path: "/opt/suricata14JIT/bin/suricata"
   logdir: "/opt/suricata14JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14JIT/etc/suricata14JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14JIT/etc/etopen/suricata14JIT-etopen-all.yaml"

 - engine: suricata-1.4JIT-test-test
   type: suricata
   version: 1.4JIT
   syntax_version: 1.3.3
   summary: "suricata 1.4JIT test config with test rules"
   path: "/opt/suricata14JIT/bin/suricata"
   logdir: "/opt/suricata14JIT/var/log/"
   # For specifying custom rules, we use the following template
   configtpl: "/opt/suricata14JIT/etc/suricata14JIT.template"
   fastlog: "alert"
   perflog: "perf.txt"
   enable: yes
   config: "/opt/suricata14JIT/etc/test/suricata14JIT-test-test.yaml"

