/usr/local/bin/pulledpork.pl -c /opt/snort294/etc/etpro/pp-snort294-etpro.config -o /opt/snort294/etc/etpro/ -k -K /opt/snort294/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort294/etc/etopen/pp-snort294-etopen.config -o /opt/snort294/etc/etopen/ -k -K /opt/snort294/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2905/etc/etpro/pp-snort2905-etpro.config -o /opt/snort2905/etc/etpro/ -k -K /opt/snort2905/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2905/etc/etopen/pp-snort2905-etopen.config -o /opt/snort2905/etc/etopen/ -k -K /opt/snort2905/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2922/etc/etpro/pp-snort2922-etpro.config -o /opt/snort2922/etc/etpro/ -k -K /opt/snort2922/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2922/etc/etopen/pp-snort2922-etopen.config -o /opt/snort2922/etc/etopen/ -k -K /opt/snort2922/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata14JIT/etc/etpro/pp-suricata14JIT-etpro.config -o /opt/suricata14JIT/etc/etpro/ -k -K /opt/suricata14JIT/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata14JIT/etc/etopen/pp-suricata14JIT-etopen.config -o /opt/suricata14JIT/etc/etopen/ -k -K /opt/suricata14JIT/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort293/etc/etpro/pp-snort293-etpro.config -o /opt/snort293/etc/etpro/ -k -K /opt/snort293/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort293/etc/etopen/pp-snort293-etopen.config -o /opt/snort293/etc/etopen/ -k -K /opt/snort293/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata13/etc/etpro/pp-suricata13-etpro.config -o /opt/suricata13/etc/etpro/ -k -K /opt/suricata13/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata13/etc/etopen/pp-suricata13-etopen.config -o /opt/suricata13/etc/etopen/ -k -K /opt/suricata13/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata13JIT/etc/etpro/pp-suricata13JIT-etpro.config -o /opt/suricata13JIT/etc/etpro/ -k -K /opt/suricata13JIT/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata13JIT/etc/etopen/pp-suricata13JIT-etopen.config -o /opt/suricata13JIT/etc/etopen/ -k -K /opt/suricata13JIT/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2931/etc/etpro/pp-snort2931-etpro.config -o /opt/snort2931/etc/etpro/ -k -K /opt/snort2931/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2931/etc/etopen/pp-snort2931-etopen.config -o /opt/snort2931/etc/etopen/ -k -K /opt/snort2931/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2841/etc/etpro/pp-snort2841-etpro.config -o /opt/snort2841/etc/etpro/ -k -K /opt/snort2841/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2841/etc/etopen/pp-snort2841-etopen.config -o /opt/snort2841/etc/etopen/ -k -K /opt/snort2841/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata135JIT/etc/etpro/pp-suricata135JIT-etpro.config -o /opt/suricata135JIT/etc/etpro/ -k -K /opt/suricata135JIT/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata135JIT/etc/etopen/pp-suricata135JIT-etopen.config -o /opt/suricata135JIT/etc/etopen/ -k -K /opt/suricata135JIT/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2923/etc/etpro/pp-snort2923-etpro.config -o /opt/snort2923/etc/etpro/ -k -K /opt/snort2923/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2923/etc/etopen/pp-snort2923-etopen.config -o /opt/snort2923/etc/etopen/ -k -K /opt/snort2923/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata131/etc/etpro/pp-suricata131-etpro.config -o /opt/suricata131/etc/etpro/ -k -K /opt/suricata131/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata131/etc/etopen/pp-suricata131-etopen.config -o /opt/suricata131/etc/etopen/ -k -K /opt/suricata131/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2861/etc/etpro/pp-snort2861-etpro.config -o /opt/snort2861/etc/etpro/ -k -K /opt/snort2861/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2861/etc/etopen/pp-snort2861-etopen.config -o /opt/snort2861/etc/etopen/ -k -K /opt/snort2861/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/snort2904/etc/etpro/pp-snort2904-etpro.config -o /opt/snort2904/etc/etpro/ -k -K /opt/snort2904/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/snort2904/etc/etopen/pp-snort2904-etopen.config -o /opt/snort2904/etc/etopen/ -k -K /opt/snort2904/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata14/etc/etpro/pp-suricata14-etpro.config -o /opt/suricata14/etc/etpro/ -k -K /opt/suricata14/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata14/etc/etopen/pp-suricata14-etopen.config -o /opt/suricata14/etc/etopen/ -k -K /opt/suricata14/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata135/etc/etpro/pp-suricata135-etpro.config -o /opt/suricata135/etc/etpro/ -k -K /opt/suricata135/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata135/etc/etopen/pp-suricata135-etopen.config -o /opt/suricata135/etc/etopen/ -k -K /opt/suricata135/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata131JIT/etc/etpro/pp-suricata131JIT-etpro.config -o /opt/suricata131JIT/etc/etpro/ -k -K /opt/suricata131JIT/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata131JIT/etc/etopen/pp-suricata131JIT-etopen.config -o /opt/suricata131JIT/etc/etopen/ -k -K /opt/suricata131JIT/etc/etopen/
/usr/local/bin/pulledpork.pl -c /opt/suricata121/etc/etpro/pp-suricata121-etpro.config -o /opt/suricata121/etc/etpro/ -k -K /opt/suricata121/etc/etpro/
/usr/local/bin/pulledpork.pl -c /opt/suricata121/etc/etopen/pp-suricata121-etopen.config -o /opt/suricata121/etc/etopen/ -k -K /opt/suricata121/etc/etopen/
